### ISSUE TITLE
Clarify README about initial database load

### ISSUE THREAD

**Issue by levlaz** [anze3db/fedidevs#26]
This line of the readme says the job takes two hours, but when I tried to run this locally I was able to get some data in just a few minutes, is this out dated? 

https://github.com/anze3db/fedidevs/blob/967f85d97cc04b32e4031bf74e7ba8334c2e070f/README.md?plain=1#L33

**Comment by anze3db** [comment]
I've ran it locally today and it took 37m31s to populate both accounts and posts from all the instances. The accounts are pretty quick though, just a couple of minutes, but fetching all the posts takes longer.

The job takes longer on my Raspberry Pi where it runs 1x per day (about 1h40m) and that's why I had ~2hrs. I've adjusted README to make all of this clearer. Let me know what you think.
