### ISSUE TITLE
Too many permissions are asked when I just want to list the packs that I was added to

### ISSUE THREAD

**Issue by joachimesque** [anze3db/fedidevs#94]
Hi!
This issue joins #50 and #90 in a neat little package:

If I wish to list the packs that contain my account, I have to accept way more permissions than needed for this specific purpose (listing the packs, possibly removing myself from a pack in the future). It might be expected that the type of people who don’t wish anything to do with being in a starter pack (while not nerfing their discoverability*), might not want to give a third-party app permissions to modify anything from their account (follow list, etc).

Reading #50, I understand that it would require two different apps, registered with different levels of permissions. That won’t facilitate this issue :)

Thanks!

----

\*  (no criticism here, I appreciate that you added the stopgap)

**Comment by anze3db** [comment]
Hey @joachimesque, thank you for opening this issue!

I would go even further and argue that you shouldn't be forced to log in to see if a certain account is in any starter packs, so I've added a search box to the "Starter Packs Containing You" page, which allows you to search for a particular user name.

I hope this addresses your issue since you now don't have to log in and share any permissions with the site to see if you are listed anywhere:

![Screenshot 2024-12-11 at 00 03 07](https://github.com/user-attachments/assets/6eb2524b-d9c0-4791-ad27-14b1f9cccf28)

Once I implement removing yourself from the list, you'll still have to log in to verify that it's you, but I'll make sure you share as few permissions as possible (I can do this without creating multiple apps, #50 is not directly related to this). Until then, please DM me if you want to get removed from any or all starter packs!

**Comment by joachimesque** [comment]
That looks perfect! Thank you for the quick answer and solution :)
